# Set PATH
PATHS=("$HOME/.local/bin/" "$HOME/bin/" "$HOME/.cask/bin")

for P in "${PATHS[@]}"; do
    if [[ -d "$P" ]]; then
        PATH="$PATH:$P"
        export PATH
    fi
done

export TERM="screen-256color"
export TERMINAL="xfce4-terminal"